### ISSUE TITLE
fanstatic is using a backport of shutil which is only requried for pre-3.3 versions of python

### ISSUE THREAD

**Issue by mckenzig** [fanstatic/fanstatic#10]
Please take a look at this PR and let me know what you think. It makes dependency on shutilwhich only apply to pre-3.3 versions of python and allows me to remove an unnecessary dependency from my app. 

https://github.com/fanstatic/fanstatic/pull/9

**Comment by janjaapdriessen** [comment]
Thank you @mckenzig, merged and released as https://pypi.org/project/fanstatic/1.3/
