### ISSUE TITLE
Move fanstatic to zopefoundation organization?

### ISSUE THREAD

**Issue by icemac** [fanstatic/fanstatic#12]
Currently `fanstatic` is mostly unmaintained.

So I'd like to propose to move the repository to the zopefoundation organization to keep it alive.
This way I could put it onto my radar and use the tools developed for zopefoundation to maintain the package.

What are your opinions about this proposal?

CC-ing the contributors in order of number of commits:

@janwijbrand @wosc @janjaapdriessen @faassen @agronholm @thefunny42 @davidjb @sallner @multani @stephane-klein @spobo1 @vangheem @shanx @michilu @kagesenshi @jhsware

**Comment by kagesenshi** [comment]
+1 from me

**Comment by icemac** [comment]
Thank you for the positive feedback, I am no going to move this repository to zopefoundation.

**Comment by icemac** [comment]
Move is done, see #13 for the changes to use zopefoundation tooling.
