### ISSUE TITLE
js.jquery_jgrowl is missing.

### ISSUE THREAD

**Issue by sallner** [fanstatic/fanstatic#3]
While testing the links in the documentation, I realized, that http://bitbucket.org/fanstatic/js.jquery_jgrowl is not yet migrated. Was this intentional or just a mistake?
It might be a good idea to move it to github as long as BB still supports the hg repos.

@thefunny42 What do you think?

**Comment by icemac** [comment]
Bitbucket no longer has the js.jquery_jgrowl repository.
